spring:
  profile: dev
  config:
    import: "optional:configserver:http://localhost:8090"
  data:
    mongodb:
      uri: "mongodb://localhost:27017/board"

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG